#!/bin/bash
python3 $PYFILE


# QUESTION

# Write a Shell script that runs a Python script.

# The Python file name will be saved in the environment variable $PYFILE

# chmod +x 0-run; to make file executable